#!/bin/sh /etc/rc.common

START=99
STOP=15

USE_PROCD=1

NAME=sguautologin
PROG="/usr/sbin/${NAME}_script"
LOG_FILE="/var/log/${NAME}.log"

. /lib/functions.sh

validate_section() {
	uci_validate "$NAME" login "$1" \
		'enabled:bool:0' \
		'username:string' \
		'password:string' \
		'auth_url:string:http://172.16.253.121/quickauth.do' \
		'check_url:string:http://2.2.2.2' \
		'night_mode:bool:0' \
		'net_start:uinteger:600' \
		'net_end:uinteger:2400' \
		'check_interval:uinteger:5' \
		'logger_interval:uinteger:600'
}

section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
	[ "$enabled" -eq 1 ]
}

start_instance() {
	local cfg="$1"

	local enabled username password auth_url check_url
	local night_mode net_start net_end check_interval logger_interval

	validate_section "$cfg" || {
		logger -t "$NAME" "validation failed for section $cfg"
		return 1
	}

	section_enabled "$cfg" || return 0

	[ -z "$username" ] && {
		logger -t "$NAME" "username is not set, skipping"
		return 1
	}

	[ -z "$password" ] && {
		logger -t "$NAME" "password is not set, skipping"
		return 1
	}

	procd_open_instance "$NAME"
	procd_set_param command "$PROG" \
		--username "$username" \
		--password "$password" \
		--auth-url "$auth_url" \
		--check-url "$check_url" \
		--night-mode "$night_mode" \
		--net-start "$net_start" \
		--net-end "$net_end" \
		--check-interval "$check_interval" \
		--logger-interval "$logger_interval"

	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param user root

	procd_close_instance
}

start_service() {
	config_load "$NAME"
	config_foreach start_instance login
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}
