#!/bin/sh /etc/rc.common

START=99
STOP=15

USE_PROCD=1

NAME=sguautologin
PROG="/usr/sbin/${NAME}_script"
LOG_FILE="/var/log/${NAME}.log"

. /lib/functions.sh

section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
	[ "$enabled" -eq 1 ]
}

start_instance() {
	local cfg="$1"

	section_enabled "$cfg" || return 0

	local username password auth_url check_url
	local night_mode net_start net_end check_interval logger_interval

	config_get username "$cfg" 'username'
	config_get password "$cfg" 'password'
	config_get auth_url "$cfg" 'auth_url'
	config_get check_url "$cfg" 'check_url'
	config_get_bool night_mode "$cfg" 'night_mode' 0
	config_get net_start "$cfg" 'net_start' 600
	config_get net_end "$cfg" 'net_end' 2400
	config_get check_interval "$cfg" 'check_interval' 5
	config_get logger_interval "$cfg" 'logger_interval' 600

	[ -z "$username" ] && {
		logger -t "$NAME" "username is not set, skipping"
		return 1
	}

	[ -z "$password" ] && {
		logger -t "$NAME" "password is not set, skipping"
		return 1
	}

	procd_open_instance "$NAME"
	procd_set_param command "$PROG" \
		--username "$username" \
		--password "$password" \
		--auth-url "$auth_url" \
		--check-url "$check_url" \
		--night-mode "$night_mode" \
		--net-start "$net_start" \
		--net-end "$net_end" \
		--check-interval "$check_interval" \
		--logger-interval "$logger_interval"

	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param user root

	procd_close_instance
}

start_service() {
	config_load "$NAME"
	config_foreach start_instance login
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}
